export const initialMenuData = [
  {
    id: 1,
    category: 'Bread',
    name: 'Artisan Croissant',
    price: 3.50,
    imageUrl: 'https://media.istockphoto.com/id/178462137/photo/croissant-isolated-on-white.jpg?s=612x612&w=0&k=20&c=jDNGlWLbufaPJuAxs5FH0-yyOC8SoPSwSE9FQKjGwJQ=',
    description: 'Flaky, buttery, and delicious. Made with premium European butter and a traditional lamination process for ultimate crispiness.',
    availableSizes: [
      { name: 'Regular', priceModifier: 0 }, // Base price is for Regular
      { name: 'Large', priceModifier: 1.00 }  // Large costs $1.00 more than Regular
    ],
    availableExtras: [
      { id: 'chocolate_filling', name: 'Chocolate Filling', price: 0.75 },
      { id: 'almond_flakes', name: 'Almond Flakes', price: 0.50 }
    ]
  },
  {
    id: 8,
    category: 'Bread',
    name: 'Integral Croissant',
    price: 3.00,
    imageUrl: 'https://media.istockphoto.com/id/178462137/photo/croissant-isolated-on-white.jpg?s=612x612&w=0&k=20&c=jDNGlWLbufaPJuAxs5FH0-yyOC8SoPSwSE9FQKjGwJQ=',
    description: 'A healthier option, made with whole wheat flour, retaining a flaky texture.',
    availableSizes: [
      { name: 'Regular', priceModifier: 0 },
    ],
    availableExtras: [
      { id: 'seeds_topping', name: 'Mixed Seeds Topping', price: 0.40 }
    ]
  },
  {
    id: 10,
    category: 'Bread',
    name: 'adsf Croissant',
    price: 3,
    imageUrl: 'https://media.istockphoto.com/id/178462137/photo/croissant-isolated-on-white.jpg?s=612x612&w=0&k=20&c=jDNGlWLbufaPJuAxs5FH0-yyOC8SoPSwSE9FQKjGwJQ=',
    description: 'Flaky, buttery, and delicious.',
    isFavorite: false,
  },
  {
    id: 19,
    category: 'Bread',
    name: 'adsf Crossant',
    price: 3,
    imageUrl: 'https://media.istockphoto.com/id/178462137/photo/croissant-isolated-on-white.jpg?s=612x612&w=0&k=20&c=jDNGlWLbufaPJuAxs5FH0-yyOC8SoPSwSE9FQKjGwJQ=',
    description: 'Flaky, buttery, and delicious.',
    isFavorite: false,
  },
  {
    id: 20,
    category: 'Bread',
    name: 'adsf Crosant',
    price: 3,
    imageUrl: 'https://media.istockphoto.com/id/178462137/photo/croissant-isolated-on-white.jpg?s=612x612&w=0&k=20&c=jDNGlWLbufaPJuAxs5FH0-yyOC8SoPSwSE9FQKjGwJQ=',
    description: 'Flaky, buttery, and delicious.',
    isFavorite: false,
  },
  {
    id: 2,
    category: 'Chicken',
    name: 'Grilled Chicken Skewers',
    price: 12.00,
    imageUrl: 'https://sailorbailey.com/wp-content/uploads/2024/03/Garlic-Parmesan-Chicken-SkewersKey.jpg',
    description: 'Juicy chicken grilled to perfection, served with a side of yogurt dip.',
    // This item has no configurable options
  },
  {
    id: 100,
    category: 'Chicken',
    name: 'Grilled Chicken Skewers',
    price: 12.00,
    imageUrl: 'https://sailorbailey.com/wp-content/uploads/2024/03/Garlic-Parmesan-Chicken-SkewersKey.jpg',
    description: 'Juicy chicken grilled to perfection.',
    isFavorite: false,
  },
  {
    id: 123,
    category: 'Chicken',
    name: 'Grilled Chicken Skewers',
    price: 12.00,
    imageUrl: 'https://sailorbailey.com/wp-content/uploads/2024/03/Garlic-Parmesan-Chicken-SkewersKey.jpg',
    description: 'Juicy chicken grilled to perfection.',
    isFavorite: false,
  },
  {
    id: 4124,
    category: 'Chicken',
    name: 'Grilled Chicken Skewers',
    price: 12.00,
    imageUrl: 'https://sailorbailey.com/wp-content/uploads/2024/03/Garlic-Parmesan-Chicken-SkewersKey.jpg',
    description: 'Juicy chicken grilled to perfection.',
    isFavorite: false,
  },
  {
    id: 15,
    category: 'Chicken',
    name: 'KFC Chicken',
    price: 12.00,
    imageUrl: 'https://sailorbailey.com/wp-content/uploads/2024/03/Garlic-Parmesan-Chicken-SkewersKey.jpg',
    description: 'Juicy chicken fried to perfection.',
    isFavorite: false,
  },
  {
    id: 11,
    category: 'Chicken',
    name: 'Lava Chicken',
    price: 12.00,
    imageUrl: 'https://sailorbailey.com/wp-content/uploads/2024/03/Garlic-Parmesan-Chicken-SkewersKey.jpg',
    description: 'Juicy chicken fried to perfection.',
    isFavorite: false,
  },
  {
    id: 3,
    category: 'Bread',
    name: 'Sourdough Loaf',
    price: 6.00,
    imageUrl: 'https://www.farmhouseonboone.com/wp-content/uploads/2023/04/sourdough-for-beginners-25-1024x683.jpg',
    description: 'Crusty exterior, soft interior.',
    isFavorite: false,
  },
  {
    id: 4,
    category: 'Sides',
    name: 'Blueberry Compote Jar',
    price: 4.50,
    imageUrl: 'https://www.resplendentkitchen.com/wp-content/uploads/2024/06/Blueberry-Compote05879-1.jpg',
    description: 'Sweet and tangy blueberry compote.',
    isFavorite: false,
  },
  {
    id: 34,
    category: 'Sides',
    name: 'Blueberry Compote Jar',
    price: 4.50,
    imageUrl: 'https://www.resplendentkitchen.com/wp-content/uploads/2024/06/Blueberry-Compote05879-1.jpg',
    description: 'Sweet and tangy blueberry compote.',
    isFavorite: false,
  },
  {
    id: 444,
    category: 'Sides',
    name: 'Blueberry Compote Jar',
    price: 4.50,
    imageUrl: 'https://www.resplendentkitchen.com/wp-content/uploads/2024/06/Blueberry-Compote05879-1.jpg',
    description: 'Sweet and tangy blueberry compote.',
    isFavorite: false,
  },
  {
    id: 44,
    category: 'Sides',
    name: 'Blueberry Compote Jar',
    price: 4.50,
    imageUrl: 'https://www.resplendentkitchen.com/wp-content/uploads/2024/06/Blueberry-Compote05879-1.jpg',
    description: 'Sweet and tangy blueberry compote.',
    isFavorite: false,
  },
  {
    id: 4444,
    category: 'Sides',
    name: 'Blueberry Compote Jar',
    price: 4.50,
    imageUrl: 'https://www.resplendentkitchen.com/wp-content/uploads/2024/06/Blueberry-Compote05879-1.jpg',
    description: 'Sweet and tangy blueberry compote.',
    isFavorite: false,
  },
  {
    id: 42,
    category: 'Sides',
    name: 'Blueberry Compote Jar',
    price: 4.50,
    imageUrl: 'https://www.resplendentkitchen.com/wp-content/uploads/2024/06/Blueberry-Compote05879-1.jpg',
    description: 'Sweet and tangy blueberry compote.',
    isFavorite: false,
  },
  {
    id: 5,
    category: 'Specials',
    name: 'Spicy Chicken Tacos',
    price: 9.75, // Price for the base set of tacos
    imageUrl: 'https://www.sugarsaltmagic.com/wp-content/uploads/2021/09/Spicy-Korean-Chicken-Tacos-B-4FEAT.jpg',
    description: 'Three spicy chicken tacos with fresh salsa, lettuce, and cheese.',
    // No 'availableSizes' for this item, for example.
    availableExtras: [
        { id: 'extra_salsa', name: 'Extra Salsa', price: 0.75 },
        { id: 'guacamole', name: 'Guacamole', price: 1.50 },
        { id: 'sour_cream', name: 'Sour Cream', price: 0.50 },
        { id: 'jalapenos', name: 'Jalapeños', price: 0.60 }
    ]
  },
  {
    id: 6,
    category: 'Salads',
    name: 'Tofu Stir-Fry',
    price: 13.80,
    imageUrl: 'https://choosingchia.com/jessh-jessh/uploads/2021/07/Weeknight-Tofu-Stir-Fry-7.jpg',
    description: 'Firm tofu with mixed veggies and feta cheese.',
    isFavorite: false,
  },
  {
    id: 7,
    category: 'Wraps',
    name: 'Turkey Wrap',
    price: 17.50,
    imageUrl: 'https://www.spendwithpennies.com/wp-content/uploads/2020/06/Turkey-Wrap-SpendWithPennies-4.jpg',
    description: 'Wheat wrap with turkey, veggies and hummus.',
    isFavorite: false,
  }
];